<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <RootNamespace></RootNamespace>
	  <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.Document.Processor" Version="25.2.2-beta" />
        <PackageReference Include="DevExpress.Drawing.Skia" Version="25.2.2-beta" />
        <PackageReference Include="System.Text.Json" Version="9.0.10" />
    </ItemGroup>
</Project>
